#!/usr/bin/env python3
"""Build the clock app: copy src/* to the site root and inline the webfonts as
data URIs into fonts.css (the workspace preview has no network access)."""
import base64, hashlib, pathlib, re, shutil, sys

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE / "src"
FONTS = HERE.parent / "fonts"
OUT = HERE

FACES = [
    ("Saans", "SaansVF.woff2", "font-weight:300 900;font-style:normal;"),
    ("Serrif", "SerrifVF.woff2", "font-weight:100 900;font-style:normal;"),
]

css = ["/* generated by build.py — do not edit by hand */", ""]
for family, fname, extra in FACES:
    path = FONTS / fname
    if not path.exists():
        sys.exit(f"missing font: {path}")
    b64 = base64.b64encode(path.read_bytes()).decode()
    css.append(
        f"@font-face{{font-family:{family};src:url(data:font/woff2;base64,{b64}) "
        f'format("woff2");{extra}font-display:swap}}'
    )
    css.append("")

(OUT / "fonts.css").write_text("\n".join(css), encoding="utf-8")
shutil.copy(SRC / "styles.css", OUT / "styles.css")
shutil.copy(SRC / "app.js", OUT / "app.js")
shutil.copy(SRC / "flags.js", OUT / "flags.js")
shutil.copy(SRC / "mapdata.js", OUT / "mapdata.js")
shutil.copy(SRC / "index.html", OUT / "index.html")
shutil.copy(SRC / "firebase-config.js", OUT / "firebase-config.js")
shutil.copy(SRC / "auth.js", OUT / "auth.js")
shutil.copy(SRC / "smate.js", OUT / "smate.js")
shutil.copy(SRC / "settings.html", OUT / "settings.html")
shutil.copy(SRC / "scribe.html", OUT / "scribe.html")

# --- sibling apps: SinghoWallet + SinghoLaunch ---
for n in ["wallet.html", "wallet.js", "cashart.js", "filesys.js", "module.html", "module.js", "launch.html", "metro.html", "metro.js", "metrofare.js", "metrodata.js", "mt_trtc.js", "mt_ty.js", "mt_ks.js", "mt_tc.js", "mb_trtc.js", "mb_ks.js", "mb_tc.js"]:
    shutil.copy(SRC / n, OUT / n)

SHIPPED = ["index.html", "styles.css", "fonts.css", "app.js", "flags.js", "mapdata.js",
           "wallet.html", "wallet.js", "cashart.js", "filesys.js", "module.html", "module.js", "launch.html",
           "firebase-config.js", "auth.js", "smate.js", "settings.html", "scribe.html",
           "metro.html", "metro.js", "metrofare.js", "metrodata.js", "mt_trtc.js", "mt_ty.js", "mt_ks.js", "mt_tc.js", "mb_trtc.js", "mb_ks.js", "mb_tc.js"]
# --- data-module versions: lets the metro page cache decoded geometry per
#     content hash, so a data update invalidates the cache automatically ---
for n in ["mb_trtc.js", "mb_ks.js", "mb_tc.js"]:
    data = (OUT / n).read_bytes()
    h = hashlib.md5(data).hexdigest()[:8]
    (OUT / n).write_text(f'export const __V = "{h}";\n' + data.decode("utf-8"), encoding="utf-8")

# --- cache-busting: version every local asset reference in the shipped HTML
# (GitHub Pages serves max-age=600; a changed query string forces a refetch
#  as soon as the HTML itself reloads, so deploys can never look "stuck") ---
ASSET_RE = re.compile(r'(href|src)="(styles\.css|fonts\.css|app\.js|flags\.js|smate\.js|auth\.js|firebase-config\.js|wallet\.js|metro\.js|mapdata\.js|metrodata\.js|module\.js|filesys\.js)"')
for html in [n for n in SHIPPED if n.endswith('.html')]:
    txt = (OUT / html).read_text(encoding='utf8')
    def bump(m):
        h = hashlib.md5((OUT / m.group(2)).read_bytes()).hexdigest()[:8]
        return f'{m.group(1)}="{m.group(2)}?v={h}"'
    (OUT / html).write_text(ASSET_RE.sub(bump, txt), encoding='utf8')

sizes = {n: (OUT / n).stat().st_size for n in SHIPPED}
print("built:", ", ".join(f"{k} {v/1024:.0f}KB" for k, v in sizes.items()))
