#!/usr/bin/env python3
"""Generate src/flags.js: IANA zone -> country code plus embedded SVG flags.

Mapping sources (all public domain, from the IANA tz database):
  zone1970.tab  canonical zones -> countries
  zone.tab      every country zone, incl. legacy aliases (Accra->GH, Oslo->NO)
  backward      Link aliases (Asia/Calcutta -> Asia/Kolkata)
  manual        UTC -> UN (the United Nations flag)
Flags come from the compact `country-flag-icons` SVG set; UN from flagcdn.
"""
import base64
import pathlib
import subprocess

HERE = pathlib.Path(__file__).resolve().parent
FLAG_DIR = HERE / "flags"
OUT = HERE / "src" / "flags.js"

TZ = "https://raw.githubusercontent.com/eggert/tz/main/"


def fetch(name):
    p = HERE / name
    if not p.exists():
        subprocess.run(["curl", "-s", "-m", "30", "-o", str(p), TZ + name], check=True)
    return p.read_text(encoding="utf-8")


zone_cc = {}

# zone1970.tab: countries, coordinates, zone
for line in fetch("zone1970.tab").splitlines():
    if not line or line.startswith("#"):
        continue
    cols = line.split("\t")
    if len(cols) >= 3:
        zone_cc[cols[2]] = cols[0].split(",")[0]

# zone.tab: country, coordinates, zone (adds the legacy per-country zones)
for line in fetch("zone.tab").splitlines():
    if not line or line.startswith("#"):
        continue
    cols = line.split("\t")
    if len(cols) >= 3:
        zone_cc[cols[2]] = cols[0]

# backward: Link <target> <alias> — resolve aliases to the target's country
links = []
for line in fetch("backward").splitlines():
    if line.startswith("Link"):
        parts = line.split()
        if len(parts) >= 3:
            links.append((parts[1], parts[2]))
for _ in range(3):  # a few passes in case of chained links
    for target, alias in links:
        if target in zone_cc:
            zone_cc.setdefault(alias, zone_cc[target])

# manual overrides
zone_cc["UTC"] = "UN"

ccs = sorted(set(zone_cc.values()))
FLAG_DIR.mkdir(exist_ok=True)


def flag_url(cc):
    if cc == "UN":
        return f"https://flagcdn.com/{cc.lower()}.svg"
    return f"https://cdn.jsdelivr.net/npm/country-flag-icons@1/3x2/{cc}.svg"


missing = [cc for cc in ccs if not (FLAG_DIR / f"{cc.lower()}.svg").exists()]
if missing:
    # one curl per file: curl's --parallel + --config mis-wires output paths
    subprocess.run(
        "xargs -a - -P 8 -n 2 sh -c 'curl -s -m 30 -o \"$2\" \"$1\"' sh",
        input="\n".join(f"{flag_url(cc)} {FLAG_DIR}/{cc.lower()}.svg" for cc in missing),
        text=True, shell=True, check=True,
    )

png = {}
for cc in ccs:
    p = FLAG_DIR / f"{cc.lower()}.svg"
    body = p.read_bytes() if p.exists() else b""
    if body and b"<svg" in body:
        png[cc] = "data:image/svg+xml;base64," + base64.b64encode(body).decode()

total = sum(len(v) for v in png.values())
js = (
    "/* generated by build_flags.py — public-domain tz data + SVG flags */\n"
    "globalThis.__KLOCK_FLAGS = {\n"
    f"  zoneCc: {zone_cc!r},\n".replace("'", '"')
    + "  png: {\n"
)
js += "".join(f'    "{cc}": "{uri}",\n' for cc, uri in sorted(png.items()))
js += "  },\n};\n"
OUT.write_text(js, encoding="utf-8")
print(f"zones mapped: {len(zone_cc)} · countries: {len(ccs)} · flags embedded: {len(png)} · payload {total/1024:.0f} KB")
