#!/usr/bin/env python3
"""Build the clock app: copy src/* to the site root and inline the webfonts as
data URIs into fonts.css (the workspace preview has no network access)."""
import base64, pathlib, shutil, sys

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE / "src"
FONTS = HERE.parent / "fonts"
OUT = HERE

FACES = [
    ("Saans", "SaansVF.woff2", "font-weight:300 900;font-style:normal;"),
    ("Serrif", "SerrifVF.woff2", "font-weight:100 900;font-style:normal;"),
]

css = ["/* generated by build.py — do not edit by hand */", ""]
for family, fname, extra in FACES:
    path = FONTS / fname
    if not path.exists():
        sys.exit(f"missing font: {path}")
    b64 = base64.b64encode(path.read_bytes()).decode()
    css.append(
        f"@font-face{{font-family:{family};src:url(data:font/woff2;base64,{b64}) "
        f'format("woff2");{extra}font-display:swap}}'
    )
    css.append("")

(OUT / "fonts.css").write_text("\n".join(css), encoding="utf-8")
shutil.copy(SRC / "styles.css", OUT / "styles.css")
shutil.copy(SRC / "app.js", OUT / "app.js")
shutil.copy(SRC / "flags.js", OUT / "flags.js")
shutil.copy(SRC / "mapdata.js", OUT / "mapdata.js")
shutil.copy(SRC / "index.html", OUT / "index.html")

# self-contained single file (works in sandboxed previews, offline, anywhere)
html = (SRC / "index.html").read_text(encoding="utf-8")
html = html.replace('<link rel="stylesheet" href="fonts.css">',
                    '<style>\n' + "\n".join(css) + '\n</style>')
html = html.replace('<link rel="stylesheet" href="styles.css">',
                    '<style>\n' + (SRC / "styles.css").read_text(encoding="utf-8") + '\n</style>')
html = html.replace('<script src="mapdata.js"></script>',
                    '<script>\n' + (SRC / "mapdata.js").read_text(encoding="utf-8") + '\n</script>')
html = html.replace('<script src="flags.js"></script>',
                    '<script>\n' + (SRC / "flags.js").read_text(encoding="utf-8") + '\n</script>')
html = html.replace('<script type="module" src="app.js"></script>',
                    '<script type="module">\n' + (SRC / "app.js").read_text(encoding="utf-8") + '\n</script>')
(OUT / "standalone.html").write_text(html, encoding="utf-8")

# --- sibling apps: SinghoWallet + SinghoLaunch ---
for n in ["wallet.html", "wallet.js", "launch.html"]:
    shutil.copy(SRC / n, OUT / n)

whtml = (SRC / "wallet.html").read_text(encoding="utf-8")
whtml = whtml.replace('<link rel="stylesheet" href="fonts.css">',
                      '<style>\n' + "\n".join(css) + '\n</style>')
whtml = whtml.replace('<link rel="stylesheet" href="styles.css">',
                      '<style>\n' + (SRC / "styles.css").read_text(encoding="utf-8") + '\n</style>')
whtml = whtml.replace('<script src="flags.js"></script>',
                      '<script>\n' + (SRC / "flags.js").read_text(encoding="utf-8") + '\n</script>')
whtml = whtml.replace('<script type="module" src="app.js"></script>',
                      '<script type="module">\n' + (SRC / "app.js").read_text(encoding="utf-8") + '\n</script>')
whtml = whtml.replace('<script type="module" src="wallet.js"></script>',
                      '<script type="module">\n' + (SRC / "wallet.js").read_text(encoding="utf-8") + '\n</script>')
(OUT / "wallet-standalone.html").write_text(whtml, encoding="utf-8")

SHIPPED = ["index.html", "styles.css", "fonts.css", "app.js", "flags.js", "mapdata.js", "standalone.html",
           "wallet.html", "wallet.js", "launch.html", "wallet-standalone.html"]
sizes = {n: (OUT / n).stat().st_size for n in SHIPPED}
print("built:", ", ".join(f"{k} {v/1024:.0f}KB" for k, v in sizes.items()))
