/* Generates src/mapdata.js: a detailed (Natural Earth 50m, public domain)
   world map as per-country SVG path data, plus a 15° graticule.
   Run: node build_map.mjs  (needs /tmp/countries-50m.json from world-atlas@2) */
import fs from 'node:fs';
import { geoNaturalEarth1, geoPath } from 'd3-geo';
import * as topojson from 'topojson-client';
import { all as isoAll } from 'iso-3166-1';

const topo = JSON.parse(fs.readFileSync('/tmp/countries-50m.json', 'utf8'));
const feats = topojson.feature(topo, topo.objects.countries).features;

const num2cc = new Map();
for (const e of isoAll()) {
  if (e.numeric) num2cc.set(String(Number(e.numeric)), e.alpha2);
}
// Natural Earth pseudo-ids we still want clickable
const NAME_CC = {
  Kosovo: 'RS',        // served by Europe/Belgrade
  'N. Cyprus': 'CY',
  Somaliland: 'SO',
};

/* cc -> zones, in the same order build_flags.py uses (population-ish first) */
const ccZones = new Map();
const addZone = (cc, z) => {
  if (!cc || !z) return;
  if (!ccZones.has(cc)) ccZones.set(cc, []);
  const l = ccZones.get(cc);
  if (!l.includes(z)) l.push(z);
};
for (const line of fs.readFileSync('zone1970.tab', 'utf8').split('\n')) {
  if (!line || line.startsWith('#')) continue;
  const [ccs, , zone] = line.split('\t');
  for (const cc of ccs.split(',')) addZone(cc, zone);
}
for (const line of fs.readFileSync('zone.tab', 'utf8').split('\n')) {
  if (!line || line.startsWith('#')) continue;
  const [cc, , zone] = line.split('\t');
  addZone(cc, zone);
}
const links = [];
for (const line of fs.readFileSync('backward', 'utf8').split('\n')) {
  const m = line.match(/^Link\s+(\S+)\s+(\S+)/);
  if (m) links.push([m[2], m[1]]); // alias -> target
}
for (const [alias, target] of links) {
  for (const [cc, zs] of ccZones) if (zs.includes(target)) addZone(cc, alias);
}

const W = 960, H = 500;
const proj = geoNaturalEarth1().fitExtent([[4, 4], [W - 4, H - 4]], { type: 'Sphere' });
const pathGen = geoPath(proj);

/* halve-pixel quantisation keeps the file small without visible loss */
const q = (d) => d.replace(/\d+\.\d+/g, (s) => {
  const v = Math.round(parseFloat(s) * 2) / 2;
  return Number.isInteger(v) ? String(v) : v.toFixed(1);
});

const cc = {};
let skipped = 0;
for (const f of feats) {
  const a2 = num2cc.get(String(Number(f.id))) || NAME_CC[f.properties?.name];
  if (!a2) { skipped++; continue; }
  const d = pathGen(f);
  if (!d) continue;
  cc[a2] = cc[a2] ? cc[a2] + d : q(d);
}
for (const k of Object.keys(cc)) cc[k] = q(cc[k]);

/* 15° meridians — the ideal timezone boundaries — as one hairline path */
const mer = [];
for (let lon = -180; lon <= 180; lon += 15) {
  const pts = [];
  for (let lat = -85; lat <= 85; lat += 5) {
    const p = proj([lon, lat]);
    if (p) pts.push(p);
  }
  mer.push(pts.map((p, i) => `${i ? 'L' : 'M'}${q(String(p[0]))},${q(String(p[1]))}`).join(''));
}
const grat = mer.join('');

const out = `/* generated by build_map.mjs — Natural Earth 50m (public domain) */
globalThis.__SINGHOAH_MAP = ${JSON.stringify({ w: W, h: H, grat, cc })};
`;
fs.writeFileSync('src/mapdata.js', out);
console.log(`mapdata.js ${(out.length / 1024).toFixed(0)} KB · ${Object.keys(cc).length} countries · skipped ${skipped}`);
